#ifndef UNICODE_CUSTOMISED_BY_ZONDA
#define UNICODE_CUSTOMISED_BY_ZONDA

#ifdef __cplusplus
extern "C" {
#endif

#ifdef _WIN32
#include <windows.h>
#endif

static inline void win_term_init() {
#ifdef _WIN32
	HANDLE hOut = GetStdHandle(STD_OUTPUT_HANDLE);
	if (hOut == INVALID_HANDLE_VALUE) {
		return;
	}
	DWORD dwMode = 0;
	if (!GetConsoleMode(hOut, &dwMode)) {
		return;
	}
	dwMode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
	if (!SetConsoleMode(hOut, dwMode)) {
		return;
	}
#endif
}

// Capital Greeks
#define _Alpha "Α"
#define _Beta "Β"
#define _Gamma "Γ"
#define _Delta "Δ"
#define _Epsilon "Ε"
#define _Zeta "Ζ"
#define _Eta "Η"
#define _Theta "Θ"
#define _Iota "Ι"
#define _Kappa "Κ"
#define _Lambda "Λ"
#define _Mu "Μ"
#define _Nu "Ν"
#define _Xi "Ξ"
#define _Omicron "Ο"
#define _Pi "Π"
#define _Rho "Ρ"
#define _Sigma "Σ"
#define _Tau "Τ"
#define _Upsilon "Υ"
#define _Phi "Φ"
#define _Chi "Χ"
#define _Psi "Ψ"
#define _Omega "Ω"

// Normal Greeks
#define _alpha "α"
#define _beta "β"
#define _gamma "γ" 
#define _delta "δ"
#define _epsilon "ε"
#define _zeta "ζ"
#define _eta "η"
#define _theta "θ"
#define _iota "ι"
#define _kappa "κ"
#define _lambda "λ"
#define _mu "μ"
#define _nu "ν"
#define _xi "ξ"
#define _omicron "ο"
#define _pi "π"
#define _rho "ρ"
#define _sigma "σ"
#define _tau "τ"
#define _upsilon "υ"
#define _phi "φ"
#define _chi "χ"
#define _psi "ψ"
#define _omega "ω"

// mathematics & sciences
#define _nabla "∇"
#define _partial "∂"
#define _belongs "∊"
#define _rbelongs "∍"
#define _Belongs "∈"
#define _nBelongs "∉"
#define _rBelongs "∋"
#define _rnBelongs "∌"
#define _QED "∎"
#define _forall "∀"
#define _exist "∃"
#define _nexist "∄"
#define _NULL "∅"
#define _prod "∏"
#define _sum "∑"
#define _plus_or_minus "±"
#define _minus_or_plus "∓"
#define _dot_or_plus "∔"
#define _composite "∘"
#define _dot "∙"
#define _sqrt "√"
#define _prop "∝"
#define _infinity "∞"
#define _vand "∨"
#define _vor "∧"
#define _uand "∪"
#define _uor "∩"
#define _int "∫"
#define _dint "∬"
#define _tint "∭"
#define _oint "∮"
#define _odint "∯"
#define _otint "∰"
#define _cuz "∵"
#define _therefore "∴"
#define _similar "∼"
#define _nsimilar "≁"
#define _congruent "≅"
#define _approxw "≈"
#define _approx "≒"
#define _neq "≠"
#define _equiv "≡"
#define _smaller_or_equal "≤"
#define _greater_or_equal "≥"
#define _subset "⊂"
#define _nsubset "⊄"
#define _rsubset "⊃"
#define _nrsubset "⊅"
#define _subset_or_equal "⊆"
#define _rsubset_or_equal "⊇"
#define _nsubset_and_neq "⊈"
#define _nrsubset_and_neq "⊉"
#define _oplus "⊕"
#define _ominus "⊖"
#define _omult "⊗"
#define _odiv "⊘"
#define _odot "⊙"
#define _vert "⊥"
#define _gaussl "⟦"
#define _gaussr "⟧"

// specials
#define _cA "𝓐"
#define _cB "𝓑"
#define _cC "𝓒"
#define _cD "𝓓"
#define _cE "𝓔"
#define _cF "𝓕"
#define _cG "𝓖"
#define _cH "𝓗"
#define _cI "𝓘"
#define _cJ "𝓙"
#define _cK "𝓚"
#define _cL "𝓛"
#define _cM "𝓜"
#define _cN "𝓝"
#define _cO "𝓞"
#define _cP "𝓟"
#define _cQ "𝓠"
#define _cR "𝓡"
#define _cS "𝓢"
#define _cT "𝓣"
#define _cU "𝓤"
#define _cV "𝓥"
#define _cW "𝓦"
#define _cX "𝓧"
#define _cY "𝓨"
#define _cZ "𝓩"
#define _ca "𝓪"
#define _cb "𝓫"
#define _cc "𝓬"
#define _cd "𝓭"
#define _ce "𝓮"
#define _cf "𝓯"
#define _cg "𝓰"
#define _ch "𝓱"
#define _ci "𝓲"
#define _cj "𝓳"
#define _ck "𝓴"
#define _cl "𝓵"
#define _cm "𝓶"
#define _cn "𝓷"
#define _co "𝓸"
#define _cp "𝓹"
#define _cq "𝓺"
#define _cr "𝓻"
#define _cs "𝓼"
#define _ct "𝓽"
#define _cu "𝓾"
#define _cv "𝓿"
#define _cw "𝔀"
#define _cx "𝔁"
#define _cy "𝔂"
#define _cz "𝔃"

#define _gA "𝔄"
#define _gB "𝔅"
#define _gC "ℭ"
#define _gD "𝔇"
#define _gE "𝔈"
#define _gF "𝔉"
#define _gG "𝔊"
#define _gH "ℌ"
#define _gI "ℑ"
#define _gJ "𝔍"
#define _gK "𝔎"
#define _gL "𝔏"
#define _gM "𝔐"
#define _gN "𝔑"
#define _gO "𝔒"
#define _gP "𝔓"
#define _gQ "𝔔"
#define _gR "ℜ"
#define _gS "𝔖"
#define _gT "𝔗"
#define _gU "𝔘"
#define _gV "𝔙"
#define _gW "𝔚"
#define _gX "𝔛"
#define _gY "𝔜"
#define _gZ "ℨ"
#define _ga "𝔞"
#define _gb "𝔟"
#define _gc "𝔠"
#define _gd "𝔡"
#define _ge "𝔢"
#define _gf "𝔣"
#define _gg "𝔤"
#define _gh "𝔥"
#define _gi "𝔦"
#define _gj "𝔧"
#define _gk "𝔨"
#define _gl "𝔩"
#define _gm "𝔪"
#define _gn "𝔫"
#define _go "𝔬"
#define _gp "𝔭"
#define _gq "𝔮"
#define _gr "𝔯"
#define _gs "𝔰"
#define _gt "𝔱"
#define _gu "𝔲"
#define _gv "𝔳"
#define _gw "𝔴"
#define _gx "𝔵"
#define _gy "𝔶"
#define _gz "𝔷"

#define _dsA "𝔸"
#define _dsB "𝔹"
#define _dsC "ℂ"
#define _dsD "𝔻"
#define _dsE "𝔼"
#define _dsF "𝔽"
#define _dsG "𝔾"
#define _dsH "ℍ"
#define _dsI "𝕀"
#define _dsJ "𝕁"
#define _dsK "𝕂"
#define _dsL "𝕃"
#define _dsM "𝕄"
#define _dsN "ℕ"
#define _dsO "𝕆"
#define _dsP "ℙ"
#define _dsQ "ℚ"
#define _dsR "ℝ"
#define _dsS "𝕊"
#define _dsT "𝕋"
#define _dsU "𝕌"
#define _dsV "𝕍"
#define _dsW "𝕎"
#define _dsX "𝕏"
#define _dsY "𝕐"
#define _dsZ "ℤ"
#define _dsa "𝕒"
#define _dsb "𝕓"
#define _dsc "𝕔"
#define _dsd "𝕕"
#define _dse "𝕖"
#define _dsf "𝕗"
#define _dsg "𝕘"
#define _dsh "𝕙"
#define _dsi "𝕚"
#define _dsj "𝕛"
#define _dsk "𝕜"
#define _dsl "𝕝"
#define _dsm "𝕞"
#define _dsn "𝕟"
#define _dso "𝕠"
#define _dsp "𝕡"
#define _dsq "𝕢"
#define _dsr "𝕣"
#define _dss "𝕤"
#define _dst "𝕥"
#define _dsu "𝕦"
#define _dsv "𝕧"
#define _dsw "𝕨"
#define _dsx "𝕩"
#define _dsy "𝕪"
#define _dsz "𝕫"
#define _ds0 "𝟘"
#define _ds1 "𝟙"
#define _ds2 "𝟚"
#define _ds3 "𝟛"
#define _ds4 "𝟜"
#define _ds5 "𝟝"
#define _ds6 "𝟞"
#define _ds7 "𝟟"
#define _ds8 "𝟠"
#define _ds9 "𝟡"

#define _up0 "⁰"
#define _up1 "¹"
#define _up2 "²"
#define _up3 "³"
#define _up4 "⁴"
#define _up5 "⁵"
#define _up6 "⁶"
#define _up7 "⁷"
#define _up8 "⁸"
#define _up9 "⁹"
#define _upa "ᵃ"
#define _upb "ᵇ"
#define _upc "ᶜ"
#define _upd "ᵈ"
#define _upe "ᵉ"
#define _upf "ᶠ"
#define _upg "ᵍ"
#define _uph "ʰ"
#define _upi "ⁱ"
#define _upj "ʲ"
#define _upk "ᵏ"
#define _upl "ˡ"
#define _upm "ᵐ"
#define _upn "ⁿ"
#define _upo "ᵒ"
#define _upp "ᵖ"
#define _upr "ʳ"
#define _ups "ˢ"
#define _upt "ᵗ"
#define _upu "ᵘ"
#define _upv "ᵛ"
#define _upw "ʷ"
#define _upx "ˣ"
#define _upy "ʸ"
#define _upz "ᶻ"
#define _up_lb "⁽"
#define _up_rb "⁾"
#define _up_plus "⁺"
#define _up_minus "⁻"
#define _up_eq "⁼"

#define _down0 "₀"
#define _down1 "₁"
#define _down2 "₂"
#define _down3 "₃"
#define _down4 "₄"
#define _down5 "₅"
#define _down6 "₆"
#define _down7 "₇"
#define _down8 "₈"
#define _down9 "₉"
#define _downa "ₐ"
#define _downe "ₑ"
#define _downh "ₕ"
#define _downi "ᵢ"
#define _downj "ⱼ"
#define _downk "ₖ"
#define _downl "ₗ"
#define _downm "ₘ"
#define _downn "ₙ"
#define _downo "ₒ"
#define _downp "ₚ"
#define _downr "ᵣ"
#define _downs "ₛ"
#define _downt "ₜ"
#define _downu "ᵤ"
#define _downv "ᵥ"
#define _downx "ₓ"
#define _down_lb "₍"
#define _down_rb "₎"
#define _down_plus "₊"
#define _down_minus "₋"
#define _down_equal "₌"

#define _l_arrow "←"
#define _r_arrow "→"
#define _d_arrow "↓"
#define _u_arrow "↑"
#define _lr_arrow "↔"
#define _ud_arrow "↕"
#define _lu_arrow "↖"
#define _ru_arrow "↗"
#define _ld_arrow "↙"
#define _rd_arrow "↘"
#define _ll_arrow "↞"
#define _rr_arrow "↠"
#define _uu_arrow "↟"
#define _dd_arrow "↡"
#define _l_varrow "↢"
#define _r_varrow "↣"
#define _ret_arrow "↩"
#define _rret_arrow "↪"
#define _l_ray "↤"
#define _r_ray "↦"
#define _u_ray "↥"
#define _d_ray "↧"
#define _hl_vect "↼"
#define _ll_vect "↽"
#define _hr_vect "⇀"
#define _lr_vect "⇁"
#define _ru_vect "↾"
#define _lu_vect "↿"
#define _rd_vect "⇂"
#define _ld_vect "⇃"
#define _dlr_arrow "⇄"
#define _dud_arrow "⇅"
#define _dhlr_arrow "⇋"
#define _l_eqarrow "⇐"
#define _r_eqarrow "⇒"
#define _u_eqarrow "⇑"
#define _d_eqarrow "⇓"
#define _lr_eqarrow "⇔"
#define _ud_eqarrow "⇕"
#define _lu_eqarrow "⇖"
#define _ru_eqarrow "⇗"
#define _rd_eqarrow "⇘"
#define _ld_eqarrow "⇙"
#define _nl_eqarrow "⇍"
#define _nr_eqarrow "⇏"
#define _l_endarrow "⇤"
#define _r_endarrow "⇥"

#define _red "\x1b[31m"
#define _green "\x1b[32m"
#define _yellow "\x1b[33m"
#define _blue "\x1b[34m"
#define _violet "\x1b[35m"
#define _cyan "\x1b[36m"
#define _white "\x1b[37m"
#define _black "\x1b[30m"
#define _lightred "\x1b[91m"
#define _lightgreen "\x1b[92m"
#define _lightyellow "\x1b[93m"
#define _lightblue "\x1b[94m"
#define _lightviolet "\x1b[95m"
#define _lightcyan "\x1b[96m"
#define _lightwhite "\x1b[97m"
#define _lightblack "\x1b[90m"

#define _b_red "\x1b[41m"
#define _b_green "\x1b[42m"
#define _b_yellow "\x1b[43m"
#define _b_blue "\x1b[44m"
#define _b_violet "\x1b[45m"
#define _b_cyan "\x1b[46m"
#define _b_white "\x1b[47m"
#define _b_black "\x1b[40m"
#define _b_lightred "\x1b[101m"
#define _b_lightgreen "\x1b[102m"
#define _b_lightyellow "\x1b[103m"
#define _b_lightblue "\x1b[104m"
#define _b_lightviolet "\x1b[105m"
#define _b_lightcyan "\x1b[106m"
#define _b_lightwhite "\x1b[107m"
#define _b_lightblack "\x1b[100m"

#define _true_color(stream, n) fprintf(stream, "\x1b[38;5;%dm", n)
#define _RGB(stream, r, g, b) fprintf(stream, "\x1b[38;2;%d;%d;%dm", r, g, b)
#define _b_true_color(stream, n) fprintf(stream, "\x1b[48;5;%dm", n)
#define _b_RGB(stream, r, g, b) fprintf(stream, "\x1b[48;2;%d;%d;%dm", r, g, b)
#define _bold "\x1b[1m"
#define _italic "\x1b[3m"
#define _underline "\x1b[4m"
#define _strikeline "\x1b[9m"
#define _reverse "\x1b[7m"
#define _end "\x1b[0m"

#define _cursor_to(stream, x, y) fprintf(stream, "\x1b[%d;%dH", y, x)
#define _cursor_u(stream, n) fprintf(stream, "\x1b[%dA", n)
#define _cursor_d(stream, n) fprintf(stream, "\x1b[%dB", n)
#define _cursor_f(stream, n) fprintf(stream, "\x1b[%dC", n)
#define _cursor_b(stream, n) fprintf(stream, "\x1b[%dD", n)
#define _cursor_save "\x1b[s"
#define _cursor_restore "\x1b[u"
#define _cursor_hide "\x1b[?25l"
#define _cursor_show "\x1b[?25h"

#define _clear "\x1b[2J\x1b[1;1H"
#define _clear_line_end "\x1b[0K"
#define _clear_line_start "\x1b[1K"
#define _clear_line "\x1b[2K"

#define _h_line "─"
#define _v_line "│"
#define _lu_corner "┌"
#define _ru_corner "┐"
#define _ld_corner "└"
#define _rd_corner "┘"
#define _l_T "├"
#define _r_T "┤"
#define _T "┬"
#define _rT "┴"
#define _cross_T "┼"
#define _h_bline "━"
#define _v_bline "┃"
#define _lu_bcorner "┏"
#define _ru_bcorner "┓"
#define _ld_bcorner "┗"
#define _rd_bcorner "┛"
#define _l_bT "┣"
#define _r_bT "┫"
#define _bT "┳"
#define _rbT "┻"
#define _cross_bT "╋"
#define _h_dline "═"
#define _v_dline "║"
#define _lu_dcorner "╔"
#define _ru_dcorner "╗"
#define _ld_dcorner "╚"
#define _rd_dcorner "╝"
#define _l_dT "╠"
#define _r_dT "╣"
#define _dT "╦"
#define _rdT "╩"
#define _cross_dT "╬"
#define _ueqv "╒"
#define _vueq "╕"
#define _vdeq "╘"
#define _deqv "╛"
#define _l_pi "╞"
#define _r_pi "╡"
#define _minus_T "╤"
#define _rT_minus "╧"
#define _neq_cross_T "╪"
#define _vvum "╓"
#define _umvv "╖"
#define _vvlm "╙"
#define _lmvv "╜"
#define _v_lT "╟"
#define _v_rT "╢"
#define _piT "╥"
#define _rpi "╨"
#define _vmv "╫"
#define _lu_rcorner "╭"
#define _ru_rcorner "╮"
#define _ld_rcorner "╰"
#define _rd_rcorner "╯"
#define _dot_hline "┄"
#define _dot_vline "┆"
#define _dot_bhline "┅"
#define _dot_bvline "┇"
#define _LtoH "╱"
#define _HtoL "╲"
#define _up "╵"
#define _right "╶"
#define _left "╴"
#define _down "╷"

#define _block "█"
#define _q1_shadow "░"
#define _q2_shadow "▒"
#define _half_shadow "▒"
#define _q3_shadow "▓"
#define _ublock "▀"
#define _dblock "▄"
#define _lblock "▌"
#define _rblock "▐"
#define _lublock "▘"
#define _ldblock "▖"
#define _rublock "▝"
#define _rdblock "▗"

#define _white_king "♔"
#define _white_queen "♕"
#define _white_rook "♖"
#define _white_bishop "♗"
#define _white_knight "♘"
#define _white_pawn "♙"
#define _black_king "♚"
#define _black_queen "♛"
#define _black_rook "♜"
#define _black_bishop "♝"
#define _black_knight "♞"
#define _black_pawn "♟"


#ifdef __cplusplus
}
#endif

#endif
